# for develop
# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1h
#   receiver: 'webhook.default'
#   routes:
#   - receiver: 'webhook.warning'
#     matchers:
#     - severity="warning"
#   - receiver: 'webhook.critical'
#     matchers:
#     - severity="critical"

# receivers:
#   - name: 'webhook.default'
#     webhook_configs:
#       - url: 'http://webhook:8080/webhook/default'
#   - name: 'webhook.warning'
#     webhook_configs:
#       - url: 'http://webhook:8080/webhook/warning'
#   - name: 'webhook.critical'
#     webhook_configs:
#       - url: 'http://webhook:8080/webhook/critical'

# for production
time_intervals:
  - name: weekdays
    time_intervals:
    - times:
      weekdays: ['monday:friday']
      location: 'Asia/Bangkok'
  - name: weekends
    time_intervals:
    - times:
      weekdays: ['sunday', 'saturday']
      location: 'Asia/Bangkok'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhook.default'
  routes:
  - receiver: 'webhook.warning'
    matchers:
    - severity="warning"
    mute_time_intervals:
    - weekdays
  - receiver: 'webhook.critical'
    matchers:
    - severity="critical"
    active_time_intervals:
    - weekdays
    - weekends

receivers:
#  - name: 'webhook.default'
#    webhook_configs:
#      - url: 'http://webhook:8080/webhook/default'
#  - name: 'webhook.warning'
#    webhook_configs:
#      - url: 'http://webhook:8080/webhook/warning'
#  - name: 'webhook.critical'
#    webhook_configs:
#      - url: 'http://webhook:8080/webhook/critical'
