services:
  grafana:
    container_name: grafana

  jaeger:
    container_name: jaeger

  loki:
    container_name: loki

  prometheus:
    container_name: prometheus

  main_service:
    container_name: main-service
    build:
      context: ./
      dockerfile: ./services/main-service/Dockerfile
    depends_on:
      - auth-service
      - user-service
      - coin-service

  auth_service:
    container_name: auth-service
    build:
      context: ./
      dockerfile: ./services/auth-service/Dockerfile
    ports:
      - 50052:50052
    depends_on:
      - user-service

  user_service:
    container_name: user-service
    build:
      context: ./
      dockerfile: ./services/user-service/Dockerfile
    ports:
      - 50051:50051
    depends_on:
      - coin-service

  coin_service:
    container_name: coin-service

