# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coin.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncoin.proto\x12\x04\x63oin\"\x1f\n\x0b\x43oinRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1c\n\x0c\x43oinResponse\x12\x0c\n\x04\x63oin\x18\x01 \x01(\t28\n\x04\x43oin\x12\x30\n\x07GetCoin\x12\x11.coin.CoinRequest\x1a\x12.coin.CoinResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coin_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COINREQUEST._serialized_start=20
  _COINREQUEST._serialized_end=51
  _COINRESPONSE._serialized_start=53
  _COINRESPONSE._serialized_end=81
  _COIN._serialized_start=83
  _COIN._serialized_end=139
# @@protoc_insertion_point(module_scope)
