# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coin_pb2 as coin__pb2


class CoinStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCoin = channel.unary_unary(
                '/coin.Coin/GetCoin',
                request_serializer=coin__pb2.CoinRequest.SerializeToString,
                response_deserializer=coin__pb2.CoinResponse.FromString,
                )


class CoinServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCoin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoinServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCoin': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoin,
                    request_deserializer=coin__pb2.CoinRequest.FromString,
                    response_serializer=coin__pb2.CoinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coin.Coin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coin.Coin/GetCoin',
            coin__pb2.CoinRequest.SerializeToString,
            coin__pb2.CoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
